const paintings6 = [
  {
    id: "5e9f5ee35eb9e72bc21af518",
    group: 0,
    page: 6,
    word: "allow",
    image: "files/07_0121.jpg",
    audio: "files/07_0121.mp3",
    audioMeaning: "files/07_0121_meaning.mp3",
    audioExample: "files/07_0121_example.mp3",
    textMeaning: "To <i>allow</i> something to happen means to let it happen.",
    textExample: "Having a ticket will <b>allow</b> you to enter the show.",
    transcription: "[əláu]",
    textExampleTranslate: "Наличие билета позволит вам войти в шоу",
    textMeaningTranslate:
      "Позволить чему-то случиться - значит позволить этому случиться",
    wordTranslate: "позволять",
  },
  {
    id: "5e9f5ee35eb9e72bc21af519",
    group: 0,
    page: 6,
    word: "announce",
    image: "files/07_0122.jpg",
    audio: "files/07_0122.mp3",
    audioMeaning: "files/07_0122_meaning.mp3",
    audioExample: "files/07_0122_example.mp3",
    textMeaning: "To <i>announce</i> something is to make it known.",
    textExample:
      "He <b>announced</b> to everyone his new idea for the company.",
    transcription: "[ənáuns]",
    textExampleTranslate: "Он объявил всем свою новую идею для компании",
    textMeaningTranslate: "Объявить что-то значит сделать это известным",
    wordTranslate: "объявить",
  },
  {
    id: "5e9f5ee35eb9e72bc21af51a",
    group: 0,
    page: 6,
    word: "beside",
    image: "files/07_0123.jpg",
    audio: "files/07_0123.mp3",
    audioMeaning: "files/07_0123_meaning.mp3",
    audioExample: "files/07_0123_example.mp3",
    textMeaning: "Someone or something <i>beside</i> you is next to you.",
    textExample: "The two brothers stood <b>beside</b> each other.",
    transcription: "[bisáid]",
    textExampleTranslate: "Два брата стояли рядом друг с другом",
    textMeaningTranslate: "Кто-то или что-то рядом с тобой рядом с тобой",
    wordTranslate: "ряд",
  },
  {
    id: "5e9f5ee35eb9e72bc21af51b",
    group: 0,
    page: 6,
    word: "challenge",
    image: "files/07_0124.jpg",
    audio: "files/07_0124.mp3",
    audioMeaning: "files/07_0124_meaning.mp3",
    audioExample: "files/07_0124_example.mp3",
    textMeaning: "A <i>challenge</i> is something difficult to complete.",
    textExample:
      "It was a <b>challenge</b> to climb to the top of the mountain.",
    transcription: "[tʃǽlindʒ]",
    textExampleTranslate: "Это была проблема - подняться на вершину горы",
    textMeaningTranslate: "Задача - это нечто сложное",
    wordTranslate: "вызов",
  },
  {
    id: "5e9f5ee35eb9e72bc21af51c",
    group: 0,
    page: 6,
    word: "claim",
    image: "files/07_0125.jpg",
    audio: "files/07_0125.mp3",
    audioMeaning: "files/07_0125_meaning.mp3",
    audioExample: "files/07_0125_example.mp3",
    textMeaning: "To <i>claim</i> means to say that something is true.",
    textExample: "He <b>claimed</b> to know why the country’s laws were weak.",
    transcription: "[kleim]",
    textExampleTranslate:
      "Он утверждал, что знает, почему законы страны были слабыми",
    textMeaningTranslate: "Утверждать - значит говорить, что что-то верно",
    wordTranslate: "запрос",
  },
  {
    id: "5e9f5ee35eb9e72bc21af51d",
    group: 0,
    page: 6,
    word: "condition",
    image: "files/07_0126.jpg",
    audio: "files/07_0126.mp3",
    audioMeaning: "files/07_0126_meaning.mp3",
    audioExample: "files/07_0126_example.mp3",
    textMeaning:
      "The <i>condition</i> of someone or something is the state that they are in.",
    textExample: "The patient’s <b>condition</b> was very good.",
    transcription: "[kəndíʃən]",
    textExampleTranslate: "Состояние пациента было очень хорошим",
    textMeaningTranslate:
      "Состояние кого-то или чего-то - это состояние, в котором они находятся",
    wordTranslate: "состояние",
  },
  {
    id: "5e9f5ee35eb9e72bc21af51e",
    group: 0,
    page: 6,
    word: "contribute",
    image: "files/07_0127.jpg",
    audio: "files/07_0127.mp3",
    audioMeaning: "files/07_0127_meaning.mp3",
    audioExample: "files/07_0127_example.mp3",
    textMeaning:
      "To <i>contribute</i> to something means to do something to make it successful.",
    textExample: "We decided to <b>contribute</b> money to the new hospital.",
    transcription: "[kəntríbjuːt]",
    textExampleTranslate: "Мы решили внести деньги в новую больницу",
    textMeaningTranslate:
      "Помогать чему-то - значит делать что-то, чтобы сделать это успешным",
    wordTranslate: "делать вклад",
  },
  {
    id: "5e9f5ee35eb9e72bc21af51f",
    group: 0,
    page: 6,
    word: "difference",
    image: "files/07_0128.jpg",
    audio: "files/07_0128.mp3",
    audioMeaning: "files/07_0128_meaning.mp3",
    audioExample: "files/07_0128_example.mp3",
    textMeaning:
      "A <i>difference</i> is a way that something is not like other things.",
    textExample:
      "The biggest <b>difference</b> between the birds is the color of their feathers.",
    transcription: "[dífərəns]",
    textExampleTranslate:
      "Самая большая разница между птицами - это цвет их перьев",
    textMeaningTranslate: "Разница - это то, что что-то не так, как другие",
    wordTranslate: "разница",
  },
  {
    id: "5e9f5ee35eb9e72bc21af520",
    group: 0,
    page: 6,
    word: "divide",
    image: "files/07_0129.jpg",
    audio: "files/07_0129.mp3",
    audioMeaning: "files/07_0129_meaning.mp3",
    audioExample: "files/07_0129_example.mp3",
    textMeaning:
      "To <i>divide</i> something is to split it into smaller parts.",
    textExample: "We <b>divided</b> the pizza.",
    transcription: "[diváid]",
    textExampleTranslate: "Мы разделили пиццу",
    textMeaningTranslate:
      "Делить что-то - значит делить это на более мелкие части",
    wordTranslate: "делить",
  },
  {
    id: "5e9f5ee35eb9e72bc21af521",
    group: 0,
    page: 6,
    word: "expert",
    image: "files/07_0130.jpg",
    audio: "files/07_0130.mp3",
    audioMeaning: "files/07_0130_meaning.mp3",
    audioExample: "files/07_0130_example.mp3",
    textMeaning:
      "An <i>expert</i> is someone who is very good at doing something.",
    textExample: "The wizard was an <b>expert</b> at magic.",
    transcription: "[ékspəːrt]",
    textExampleTranslate: "Волшебник был экспертом в магии",
    textMeaningTranslate: "Эксперт - это тот, кто очень хорошо делает что-то",
    wordTranslate: "эксперт",
  },
  {
    id: "5e9f5ee35eb9e72bc21af522",
    group: 0,
    page: 6,
    word: "famous",
    image: "files/07_0131.jpg",
    audio: "files/07_0131.mp3",
    audioMeaning: "files/07_0131_meaning.mp3",
    audioExample: "files/07_0131_example.mp3",
    textMeaning: "A <i>famous</i> person or thing is well known.",
    textExample: "The Eiffel Tower in Paris is very <b>famous</b>.",
    transcription: "[féiməs]",
    textExampleTranslate: "Эйфелева башня в Париже очень известна",
    textMeaningTranslate: "Известный человек или вещь хорошо известна",
    wordTranslate: "известный",
  },
  {
    id: "5e9f5ee35eb9e72bc21af523",
    group: 0,
    page: 6,
    word: "force",
    image: "files/07_0132.jpg",
    audio: "files/07_0132.mp3",
    audioMeaning: "files/07_0132_meaning.mp3",
    audioExample: "files/07_0132_example.mp3",
    textMeaning: "<i>Force</i> is a person’s strength or power.",
    textExample: "He used all his <b>force</b> to try and open the door.",
    transcription: "[fɔːrs]",
    textExampleTranslate:
      "Он использовал все свои силы, чтобы попытаться открыть дверь",
    textMeaningTranslate: "Сила - это сила или сила человека",
    wordTranslate: "сила",
  },
  {
    id: "5e9f5ee35eb9e72bc21af524",
    group: 0,
    page: 6,
    word: "harm",
    image: "files/07_0133.jpg",
    audio: "files/07_0133.mp3",
    audioMeaning: "files/07_0133_meaning.mp3",
    audioExample: "files/07_0133_example.mp3",
    textMeaning: "To cause <i>harm</i> is to hurt someone or damage something.",
    textExample:
      "A hot iron can cause great <b>harm</b> if you are not careful.",
    transcription: "[hɑːrm]",
    textExampleTranslate:
      "Горячий утюг может причинить большой вред, если вы не будете осторожны",
    textMeaningTranslate:
      "Причинить вред - значит причинить кому-то боль или что-то повредить",
    wordTranslate: "вред",
  },
  {
    id: "5e9f5ee35eb9e72bc21af525",
    group: 0,
    page: 6,
    word: "lay",
    image: "files/07_0134.jpg",
    audio: "files/07_0134.mp3",
    audioMeaning: "files/07_0134_meaning.mp3",
    audioExample: "files/07_0134_example.mp3",
    textMeaning:
      "To <i>lay</i> means to put or place in a horizontal or flat position.",
    textExample: "Don’t <b>lay</b> your socks on the floor.",
    transcription: "[lei]",
    textExampleTranslate: "Не кладите носки на пол",
    textMeaningTranslate:
      "Уложить означает положить или поместить в горизонтальное или плоское положение",
    wordTranslate: "лежал",
  },
  {
    id: "5e9f5ee35eb9e72bc21af526",
    group: 0,
    page: 6,
    word: "peace",
    image: "files/07_0135.jpg",
    audio: "files/07_0135.mp3",
    audioMeaning: "files/07_0135_meaning.mp3",
    audioExample: "files/07_0135_example.mp3",
    textMeaning: "<i>Peace</i> is a time without war.",
    textExample: "A white dove is a symbol of <b>peace</b>.",
    transcription: "[piːs]",
    textExampleTranslate: "Белый голубь - символ мира",
    textMeaningTranslate: "Мир - это время без войны",
    wordTranslate: "мир",
  },
  {
    id: "5e9f5ee35eb9e72bc21af527",
    group: 0,
    page: 6,
    word: "prince",
    image: "files/07_0136.jpg",
    audio: "files/07_0136.mp3",
    audioMeaning: "files/07_0136_meaning.mp3",
    audioExample: "files/07_0136_example.mp3",
    textMeaning: "A <i>prince</i> is the son of a king.",
    textExample: "The <b>prince</b> and the princess were married.",
    transcription: "[prins]",
    textExampleTranslate: "Принц и принцесса были женаты",
    textMeaningTranslate: "Принц - сын короля",
    wordTranslate: "принц",
  },
  {
    id: "5e9f5ee35eb9e72bc21af528",
    group: 0,
    page: 6,
    word: "protect",
    image: "files/07_0137.jpg",
    audio: "files/07_0137.mp3",
    audioMeaning: "files/07_0137_meaning.mp3",
    audioExample: "files/07_0137_example.mp3",
    textMeaning: "To <i>protect</i> someone is to stop them from getting hurt.",
    textExample: "Firemen <b>protect</b> us from fires.",
    transcription: "[prətékt]",
    textExampleTranslate: "Пожарные защищают нас от пожаров",
    textMeaningTranslate: "Защищать кого-то - значит не дать им пострадать",
    wordTranslate: "защита",
  },
  {
    id: "5e9f5ee35eb9e72bc21af529",
    group: 0,
    page: 6,
    word: "sense",
    image: "files/07_0138.jpg",
    audio: "files/07_0138.mp3",
    audioMeaning: "files/07_0138_meaning.mp3",
    audioExample: "files/07_0138_example.mp3",
    textMeaning:
      "To <i>sense</i> something is to know about it without being told.",
    textExample: "I could <b>sense</b> that he was watching me.",
    transcription: "[sens]",
    textExampleTranslate: "Я чувствовал, что он смотрит на меня",
    textMeaningTranslate:
      "Чувствовать что-то значит знать об этом, не сказав ничего",
    wordTranslate: "смысл",
  },
  {
    id: "5e9f5ee35eb9e72bc21af52a",
    group: 0,
    page: 6,
    word: "sudden",
    image: "files/07_0139.jpg",
    audio: "files/07_0139.mp3",
    audioMeaning: "files/07_0139_meaning.mp3",
    audioExample: "files/07_0139_example.mp3",
    textMeaning: "When something is <i>sudden</i>, it happens very quickly.",
    textExample: "He felt a <b>sudden</b> pain in his chest.",
    transcription: "[sʌ́dn]",
    textExampleTranslate: "Он почувствовал внезапную боль в груди",
    textMeaningTranslate: "Когда что-то внезапно, это происходит очень быстро",
    wordTranslate: "внезапное",
  },
  {
    id: "5e9f5ee35eb9e72bc21af52b",
    group: 0,
    page: 6,
    word: "therefore",
    image: "files/07_0140.jpg",
    audio: "files/07_0140.mp3",
    audioMeaning: "files/07_0140_meaning.mp3",
    audioExample: "files/07_0140_example.mp3",
    textMeaning: "<i>Therefore</i> means for this reason.",
    textExample: "He is fat. <b>Therefore</b>, he should go on a diet.",
    transcription: "[ðɛ́əːrfɔ̀ːr]",
    textExampleTranslate: "Он толстый. Поэтому ему следует сесть на диету",
    textMeaningTranslate: "Поэтому значит по этой причине",
    wordTranslate: "следовательно",
  },
]

export default paintings6
